export const Category = [
  { id: '1', name: 'Work', fa: 'کار', color: '#FF6B6B', icon: '💼' },
  { id: '2', name: 'Personal', fa: 'شخصی', color: '#4ECDC4', icon: '👤' },
  { id: '3', name: 'Health', fa: 'سلامت', color: '#45B7D1', icon: '🏥' },
  { id: '4', name: 'Education', fa: 'تحصیل', color: '#96CEB4', icon: '📚' },
  { id: '5', name: 'Finance', fa: 'مالی', color: '#FFEAA7', icon: '💰' },
  { id: '6', name: 'Travel', fa: 'سفر', color: '#DDA0DD', icon: '✈️' },
  { id: '7', name: 'Shopping', fa: 'خرید', color: '#98D8C8', icon: '🛒' },
  { id: '8', name: 'Fitness', fa: 'ورزش', color: '#FFA07A', icon: '🏋️' },
  { id: '9', name: 'Meditation', fa: 'مدیتیشن', color: '#A29BFE', icon: '🧘' },
  { id: '10', name: 'Reading', fa: 'مطالعه', color: '#F8B195', icon: '📖' },
  { id: '11', name: 'Cooking', fa: 'آشپزی', color: '#FDCB6E', icon: '👨‍🍳' },
  { id: '12', name: 'Cleaning', fa: 'نظافت', color: '#C5E1A5', icon: '🧹' },
  { id: '13', name: 'Meetings', fa: 'جلسات', color: '#FFD3B6', icon: '📅' },
  { id: '14', name: 'Social', fa: 'اجتماعی', color: '#74B9FF', icon: '💬' },
  { id: '15', name: 'Projects', fa: 'پروژه‌ها', color: '#B2BEC3', icon: '🗂️' },
  { id: '16', name: 'Habits', fa: 'عادت‌ها', color: '#E17055', icon: '✅' },
  { id: '17', name: 'Sleep', fa: 'خواب', color: '#636e72', icon: '😴' },
  { id: '18', name: 'Entertainment', fa: 'سرگرمی', color: '#FAB1A0', icon: '🎮' },
  { id: '19', name: 'Birthday', fa: 'تولد', color: '#F06292', icon: '🎂' },
  { id: '20', name: 'Other', fa: 'سایر', color: '#D3D3D3', icon: '📌' },
];
