export const Category = [
  { id: '1', name: 'Work', color: '#FF6B6B', icon: '💼' },
  { id: '2', name: 'Personal', color: '#4ECDC4', icon: '👤' },
  { id: '3', name: 'Health', color: '#45B7D1', icon: '🏥' },
  { id: '4', name: 'Education', color: '#96CEB4', icon: '📚' },
  { id: '5', name: 'Finance', color: '#FFEAA7', icon: '💰' },
  { id: '6', name: 'Travel', color: '#DDA0DD', icon: '✈️' },
  { id: '7', name: 'Shopping', color: '#98D8C8', icon: '🛒' },
  { id: '8', name: 'Fitness', color: '#FFA07A', icon: '🏋️' },
  { id: '9', name: 'Meditation', color: '#A29BFE', icon: '🧘' },
  { id: '10', name: 'Reading', color: '#F8B195', icon: '📖' },
  { id: '11', name: 'Cooking', color: '#FDCB6E', icon: '👨‍🍳' },
  { id: '12', name: 'Cleaning', color: '#C5E1A5', icon: '🧹' },
  { id: '13', name: 'Meetings', color: '#FFD3B6', icon: '📅' },
  { id: '14', name: 'Social', color: '#74B9FF', icon: '💬' },
  { id: '15', name: 'Projects', color: '#B2BEC3', icon: '🗂️' },
  { id: '16', name: 'Habits', color: '#E17055', icon: '✅' },
  { id: '17', name: 'Sleep', color: '#636e72', icon: '😴' },
  { id: '18', name: 'Entertainment', color: '#FAB1A0', icon: '🎮' },
  { id: '19', name: 'Birthday', color: '#F06292', icon: '🎂' },
  { id: '20', name: 'Other', color: '#D3D3D3', icon: '📌' },
];
